language: cpp
dist: xenial
compiler: gcc

addons: 
  apt: 
    packages: 
      - libboost-all-dev


install:
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

script: 
 - ./install_urho3d
 - ln -s ../Urho3D/bin/Data
 - ln -s ../Urho3D/bin/CoreData
 - qmake -qt=qt5 travis_qmake_gcc_cpp11_urho3d.pro
 - make --silent
